all: grader normal weighted_torus

grader:
	@echo Building ../src/grader...
	$(MAKE) -C ../src/grader

normal:
	@echo Building ../src/normal...
	$(MAKE) -C ../src/normal

weighted_torus:
	@echo Building ../src/weighted_torus...
	$(MAKE) -C ../src/weighted_torus
